services:
  lvim:
    build: .
    image: lvim
    stdin_open: true
    tty: true
    volumes:
      #- lvimpacker:/root/.local/share/lunarvim/site/pack/packer
      - lvimconfig:/root/.config
      #- masonpackages:/root/.local/share/nvim/mason/packages
      - local:/root/.local
      - $PWD:/files

volumes:
  lvimconfig:

  local:
